gumi2inside/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
]

gumi2inside/announcements/urls.py
from django.urls import path
from . import views

app_name = "announcements"
urlpatterns = [
    path("", views.announcement_list, name="announcement"),
]

gumi2inside/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("complete/", views.complete, name="complete"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("articles_list/", views.articles_list, name="articles_list"),
    path("comment/<int:pk>/", views.comment, name="comment"),
    path("like/<int:article_pk>/", views.like_article, name="like_article"),
    path("dislike/<int:article_pk>/", views.dislike_article, name="dislike_article"),
    path("comment_like/<int:comment_pk>/", views.like_comment, name="like_comment"),
    path("comment_dislike/<int:comment_pk>/", views.dislike_comment, name="dislike_comment"),
    path('polls_list/', views.polls_list, name='polls_list'),
    path('polls_list/user/', views.polls_list_by_user, name='polls_list_by_user'),
    path('polls_add/', views.polls_add, name='polls_add'),
    path('polls_edit/<int:poll_id>/', views.polls_edit, name='polls_edit'),
    path('polls_delete/<int:poll_id>/', views.polls_delete, name='polls_delete'),
    path('polls_end/<int:poll_id>/', views.polls_endpoll, name='polls_end_poll'),
    path('polls_edit/<int:poll_id>/choice/add/', views.polls_add_choice, name='polls_add_choice'),
    path('polls_edit/choice/<int:choice_id>/', views.polls_choice_edit, name='polls_choice_edit'),
    path('polls_delete/choice/<int:choice_id>/',
         views.polls_choice_delete, name='choice_delete'),
    path('polls_<int:poll_id>/', views.poll_detail, name='polls_detail'),
    path('polls_<int:poll_id>/vote/', views.poll_vote, name='polls_vote'),
]

gumi2inside/gumi2inside/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('ciders/', include('ciders.urls')),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('announcements/', include('announcements.urls')),
    path('rboards', include('rboards.urls')),
    path('admin_img/', include('admin_img.urls')),
]

gumi2inside/rboards/urls.py
from django.urls import path
from . import views

app_name = "rboards"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("complete/", views.complete, name="complete"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("rboards_list/", views.rboards_list, name="rboards_list"),
    path("comment/<int:pk>/", views.comment, name="comment"),
    path("like/<int:article_pk>/", views.like_article, name="like_article"),
    path("dislike/<int:article_pk>/", views.dislike_article, name="dislike_article"),
    path("comment_like/<int:comment_pk>/", views.like_comment, name="like_comment"),
    path("comment_dislike/<int:comment_pk>/", views.dislike_comment, name="dislike_comment"),
]

gumi2inside/articles/models.py
from django.db import models
from django.conf import settings
from accounts.models import User
from django.utils import timezone
import secrets

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    textsize = models.TextField()
    red = models.TextField()
    green = models.TextField()
    blue = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    visited_count = models.IntegerField()
    like_count = models.IntegerField(default=0)
    dislike_count = models.IntegerField(default=0)
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="liked_articles")
    disliked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="disliked_articles")
    img_url = models.TextField()
    status = models.TextField(default="Article")

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    origin_article = models.ForeignKey('Article', on_delete=models.CASCADE)
    like_count = models.IntegerField(default=0)
    dislike_count = models.IntegerField(default=0)
    comment_liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="liked_comments")
    comment_disliked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="disliked_comments")


class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)  # created_at 필드에 현재 시간을 저장
    active = models.BooleanField(default=True)

    def user_can_vote(self, user):
        """ 
        Return False if user already voted
        """
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def get_result_dict(self):
        res = []
        for choice in self.choice_set.all():
            d = {}
            alert_class = ['primary', 'secondary', 'success',
                           'danger', 'dark', 'warning', 'info']

            d['alert_class'] = secrets.choice(alert_class)
            d['text'] = choice.choice_text
            d['num_votes'] = choice.get_vote_count
            if not self.get_vote_count:
                d['percentage'] = 0
            else:
                d['percentage'] = (choice.get_vote_count /
                                   self.get_vote_count)*100

            res.append(d)
        return res

    def __str__(self):
        return self.text


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def __str__(self):
        return f"{self.poll.text[:25]} - {self.choice_text[:25]}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.poll.text[:15]} - {self.choice.choice_text[:15]} - {self.user.username}'

gumi2inside/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Article, Comment, Poll, Choice, Vote
from common.models import Lunch
from datetime import datetime
from announcements.models import announcement
from django.contrib.auth.decorators import login_required
from img_upload import img_upload,img_view
from admin_img.models import Carousel
from .forms import PollAddForm, EditPollForm, ChoiceAddForm
from django.core.paginator import Paginator
from datetime import datetime
from announcements.models import announcement
from django.utils import timezone


# Create your views here.
def home(request):
    announcements = announcement.objects.order_by('-id')
    announce = ''
    a_menu = Lunch.objects.filter(menuCourseType='AA').order_by('-date').first()
    c_menu = Lunch.objects.filter(menuCourseType='BB').order_by('-date').first()
    
    if announcements.exists():
        for i in announcements:
            announce = i
            break
    carousel1 = Carousel.objects.get(number=1)
    carousel2 = Carousel.objects.get(number=2)
    carousel3 = Carousel.objects.get(number=3)
    
    context ={
        'announce':announce,
        'a_menu':a_menu,
        'b_menu':c_menu,
        'announce' : announce,
        'carousel1' : carousel1.img_url,
        'carousel2' : carousel2.img_url,
        'carousel3' : carousel3.img_url,
    }    
    return render(request, "articles/home.html", context)



def new(request):
    return render(request, "articles/new.html")


def create(request):
    title = request.POST.get("title")
    content = request.POST.get("content")
    textsize = request.POST.get("textsize")
    red = request.POST.get("red")
    green = request.POST.get("green")
    blue = request.POST.get("blue")
    article = Article(textsize=textsize, red=red, green=green, blue=blue,title=title, content=content, visited_count = 0, like_count = 0, dislike_count = 0)
    article.save()
    if 'file' in request.FILES:
        img_upload(request, article)
    return render(request, "articles/complete.html")


def comment(request, pk):
    content = request.POST.get("comment")
    comment = Comment(content=content, like_count = 0, dislike_count = 0,)
    comment.origin_article = Article.objects.get(pk=pk)
    comment.save()
    return redirect(reverse('articles:detail', kwargs={'pk': pk}))



def complete(request):
    return redirect("articles:articles_list")


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    time = article.created_at
    new_datetime=''
    new_datetime+=str(time)[0:11]
    new_datetime+=str(time)[11:16]
    comments = article.comment_set.all()
    article.visited_count += 1
    article.save()
        
    context = {
        "pk": pk,
        "title": article.title,
        "content": article.content,
        "new_datetime": new_datetime,
        "comments": comments,
        "comments_count": len(comments),
        "visited_count": article.visited_count,
        "like" : article.like_count,
        "dislike" : article.dislike_count,
        "textsize" : article.textsize,
        "red" : article.red,
        "green" : article.green,
        "blue" : article.blue,
        "liked_users": article.liked_users.all(),  # 좋아요를 누른 사용자 목록
        "disliked_users": article.disliked_users.all()
    }
    context = img_view(article,context)
    
    return render(request, "articles/detail.html", context)


def articles_list(request):
    articles = Article.objects.order_by('-id')
  

    context = {
        'articles' : articles,
    }
    return render(request, "articles/articles_list.html", context)
 


@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect("articles:articles_list")


@login_required
def like_article(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    user = request.user

    if user in article.liked_users.all():
        # 이미 좋아요를 누른 경우, 취소 처리
        article.liked_users.remove(user)
        article.like_count -= 1
        article.visited_count -= 1
        article.save()
        return redirect('articles:detail', pk=article.pk)
    
    if user in article.disliked_users.all():
        article.disliked_users.remove(user)
        article.dislike_count -= 1
    # 좋아요 처리
    article.liked_users.add(user)
    article.like_count += 1
    article.visited_count -= 1
    article.save()
    return redirect('articles:detail', pk=article.pk)


@login_required
def dislike_article(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    user = request.user

    if user in article.disliked_users.all():
        # 이미 싫어요를 누른 경우, 취소 처리
        article.disliked_users.remove(user)
        article.dislike_count -= 1
        article.visited_count -= 1
        article.save()
        return redirect('articles:detail', pk=article.pk)
    
    if user in article.liked_users.all():
        article.liked_users.remove(user)
        article.like_count -= 1
    # 싫어요 처리
    article.disliked_users.add(user)
    article.dislike_count += 1
    article.visited_count -= 1
    article.save()
    return redirect('articles:detail', pk=article.pk)


@login_required
def like_comment(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.origin_article
    user = request.user

    if user in comment.comment_liked_users.all():
        # 이미 좋아요를 누른 경우, 취소 처리
        comment.comment_liked_users.remove(user)
        comment.like_count -= 1
    else:
        if user in comment.comment_disliked_users.all():
            comment.comment_disliked_users.remove(user)
            comment.dislike_count -= 1
        # 좋아요 처리
        comment.comment_liked_users.add(user)
        comment.like_count += 1
        
    article = comment.origin_article
    article.visited_count -= 1
    article.save()
    comment.save()
    return redirect('articles:detail', pk=article.pk)


@login_required
def dislike_comment(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    print(comment.origin_article)
    user = request.user

    if user in comment.comment_disliked_users.all():
        # 이미 싫어요를 누른 경우, 취소 처리
        comment.comment_disliked_users.remove(user)
        comment.dislike_count -= 1
    else:
    
        if user in comment.comment_liked_users.all():
            comment.comment_liked_users.remove(user)
            comment.like_count -= 1
        # 싫어요 처리
        comment.comment_disliked_users.add(user)
        comment.dislike_count += 1
    article = comment.origin_article
    article.visited_count -= 1
    article.save()
    comment.save()
    return redirect('articles:detail', pk=article.pk)

def polls_list(request):
    all_polls = Poll.objects.order_by('-id')
    paginator = Paginator(all_polls, 10)  # Show 6 contacts per page
    page = request.GET.get('page')
    polls = paginator.get_page(page)

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    # current_time = timezone.now()
    # time_difference = current_time - poll.created_at
    context = {
        'polls': polls,
        'params': params,
        
    }
    return render(request, 'articles/polls_list.html', context)


@login_required()
def polls_list_by_user(request):
    all_polls = Poll.objects.filter(owner=request.user)
    paginator = Paginator(all_polls, 10)  # Show 7 contacts per page

    page = request.GET.get('page')
    polls = paginator.get_page(page)

    context = {
        'polls': polls,
    }
    return render(request, 'articles/polls_list.html', context)


@login_required()
def polls_add(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PollAddForm(request.POST)
            if form.is_valid:
                poll = form.save(commit=False)
                poll.owner = request.user
                poll.save()
                new_choice1 = Choice(
                    poll=poll, choice_text=form.cleaned_data['choice1']).save()
                new_choice2 = Choice(
                    poll=poll, choice_text=form.cleaned_data['choice2']).save()

                
                return redirect('articles:polls_list')
        else:
            form = PollAddForm()
        context = {
            'form': form,
        }
        return render(request, 'articles/add_poll.html', context)
    else:
        return redirect('articles:polls_list')


@login_required
def polls_edit(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return redirect('home')

    if request.method == 'POST':
        form = EditPollForm(request.POST, instance=poll)
        if form.is_valid:
            form.save()
            
            return redirect("articles:polls_list")

    else:
        form = EditPollForm(instance=poll)

    return render(request, "articles/poll_edit.html", {'form': form, 'poll': poll})


@login_required
def polls_delete(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return redirect('home')
    poll.delete()
    
    return redirect("articles:polls_list")


@login_required
def polls_add_choice(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return redirect('home')

    if request.method == 'POST':
        form = ChoiceAddForm(request.POST)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            
            return redirect('articles:polls_edit', poll.id)
    else:
        form = ChoiceAddForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/add_choice.html', context)


@login_required
def polls_choice_edit(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)

gumi2inside/articles/templates/articles/add_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
           
            {% else %}
            <h2>항목 추가</h2>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                {% if edit_choice %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:choice_delete' choice.id %}" role="button" onclick="return confirm('지우시겠습니까?')">삭제</a>
                {% else %}
                <button type="submit" class="btn btn-primary">추가</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

gumi2inside/articles/templates/articles/articles_list.html
{% load static %}
{% load custom_filters %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>구미2반 커뮤니티!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" href="style.css"> {% endcomment %}
    <link rel="shortcut icon" href="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/favicon.ico">
    <style>
      .bg_top{
        width: 100%;
        height: 100%;
        background-color: #ffef6b;
        position: absoulte ;
        top: 0;
        margin: 0;
       
      }
      .card.border-light {
        border-color: white;
      }
      .bg_top_2{
          width: 100%;
          
          background-color: white;
          position: absoulte ;
          top: 0;
          margin: 0;
        }
      .bg_card{
          
          background-repeat: no-repeat;
          background-size : 100% 100% ;
          height: auto;
      }
      .border1{
              border: 2px black solid;
      }
      .imagesize{
          height: 300px;
          width: 300px;
          margin-top: 0px;
          
      }
      footer{
        display: inline;
      }
      .right{
        
      }
    </style>
  </head>
  <body>
    <!-- 네비게이터 -->
        <header class=" border-bottom fixed-top">
            <nav class="navbar navbar-expand-lg navbar-light bg-white">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <img src="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/logo.png" height="30px" alt="로고">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse space-between" id="navbarSupportedContent">
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">홈</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'articles:articles_list' %}">익명 게시판</a>
                          </li> 
                          <li>
                            <a class="nav-link" href="{% url 'rboards:rboards_list' %}">실명 게시판</a>
                          </li>
                          <li>
                            <a class="nav-link" href="{% url 'articles:polls_list' %}">투표 게시판</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link fw-bold" style="color: #8a2be2;" href="{% url 'ciders:main' %}">사이다</a>
                          </li> 
                      </ul>
                      <ul class="navbar-nav mb-2 mb-lg-0">
                          {% if request.user.is_authenticated %}
                        
                          <li class="nav-item">
                            <a class="nav-link fw-bold text-body-tertiary" href="{% url 'accounts:update' %}?next={{ request.path }}">회원정보 수정</a>
                          </li> 
                          <li class="nav-item">
                            <form action="{% url "accounts:logout" %}" method="POST">
                              {% csrf_token %}
                              <input type="submit" value="로그아웃" class="nav-link fw-bold text-body-tertiary" >
                            </form>
                          </li>
    
                          {% else %}
                        
                          <li class="nav-item">
                            <a class="nav-link fw-bold" href="{% url 'accounts:signup' %}?next={{ request.path }}">회원가입</a>
                            </form>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link fw-bold" href="{% url 'accounts:login' %}?next={{ request.path }}">로그인</a>
                          </li> 
                          {% endif %}
                      </ul>
                    
                  </div>
                </div>
            </nav>
            
        </header>
        
    
    <!-- 네비게이터 -->
    <div class= "bg_top">
      <div class='container ' style="padding-left: 100px; padding-top: 55px; padding-right: 100px; ">
        <div class="row bg-white">
    
          {% for article in articles%}
          <div  class="container col-md-12 ">
            <div class="row">
              <form method="POST" action="{% url 'articles:detail' article.pk%}">
                {% csrf_token %}
                <div class="col-md-6 offset-3 ">
                  <div class="card text-black mt-5">
                    <button class="btn btn-outline-none text-truncate" type='submit'>
                      <div class="row card-title text-truncate  align-items-center">
                        <span class='col-9 ps-5 pe-2 text-start text-truncate' style='font-size: 1.8rem;'>{{article.title}}</span>
                        <span style='float: right;' class="text-muted col-3 align-items-center">{{ article.created_at|time_difference_with_now }}</span>
                      </div>   
                      <div class='row justify-content-start align-items-center mx-0'>
                        <p class='mb-1 pb-2 col-3'>💬{{ article.comment_set.all|length }}</p>
                      </div>
                    </button>   
                  </div>
                </div>
              </form>
            {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
    
    <a href="{% url 'articles:new' %}"><img src="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/gcova.png" class='imagesize fixed-bottom'></a>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

gumi2inside/articles/templates/articles/detail.html
{% extends "base.html" %}
{% load humanize %}
{% load custom_tag %}
{% block style %}
.bg_top_2{
  width: 100%;
  height: 330px;
  background-color: white;
  position: absoulte ;
  top: 0;
  margin: 0;
}
.bg-yellow{
  background-color: #ffe651;
}
.bg-realgrey{
  border: 1px solid lightgrey;
}

{% endblock style %} 

{% block content %}
<div class='bg_top_2'>
  <div class="container mt-5 mb-3">
    <div>
      <strong class="text-break"> {{ title }}</strong>
      <span style="float: right;">작성시간 : {{ new_datetime }}</span>
      <div style="clear: both;"></div>
      <hr>
    </div>
      {% if img_url %}
        <img src="{{ img_url }}" alt="image" style="max-width: 90%;">
      {% endif %}
      <div>
        <!--여기에 클래스 추가-->
        <p class="text-break" style="color: rgb({{red|safe}}, {{green|safe}}, {{blue|safe}}); font-size : {{textsize|safe}}px; white-space: pre-line" > {{content|urlize|safe|target_blank}}</p>
      </div>
      <hr>
    <p>조회수 : {{ visited_count }} </p>
    {% comment %} 게시글 추천 / 비추 {% endcomment %}
    {% comment %} <div class="row">
      <div class='col-3 border border-0'>
        <form method="POST" action="{% url 'articles:like_article' pk %}">
          {% csrf_token %}
          {% if request.user in liked_users %}
          <button class='btn btn-primary border border-0' type="submit">🧡 추천!</button>
          {% else %}
          <button class='btn btn-outline-primary' type="submit">🧡 추천!</button>
          {% endif %}
          <span> {{ like }} </span>
        </form>
      </div>
      <div class='col-3 border border-0'>
        <form method="POST" action="{% url 'articles:dislike_article' pk %}">
          {% csrf_token %}
          {% if request.user in disliked_users %}
          <button class="btn btn-danger" type="submit">👎 비추</button>
          {% else %}
          <button class="btn btn-outline-danger" type="submit">👎 비추</button>
          {% endif %}
          <span> {{ dislike }} </span>
        </form>
      </div> 
    </div> {% endcomment %}
    {% comment %} 추천 비추 코드 끝 {% endcomment %}
  </div>
  <div class="container mt-5">
    <strong>댓글 ({{comments_count}}) </strong>
    <form action="{% url 'articles:comment' pk %}" method="POST">
      {% csrf_token %}
      <textarea name="comment" id="comment" row="3" style="width: 100%;"></textarea>
      <input class="btn btn-light btn-lg text-center me-5" type="submit" value="댓글 쓰기">
    </form>
  </div>
  {% for comment in comments %}
  <div class="container my-4 pt-4 pb-2 px-5 bg-light bg-realgrey">
    <div class="row">
      <div class='col-8 col-md-9 col-lg-10 align-self-center'>
        <div class="mb-3">
          <p><span class="pe-3">{{ comment.created_at }}</span> <span class="border border-dark-subtle"></span> <span class="ps-3 text-body-tertiary">익명</span> </p>
        </div>
        <div class="my-2 mx-5 text-break" style="white-space: pre-line">{{comment.content|urlize|safe|target_blank}} </div>
      </div>
      <div class="col-4 col-md-3 col-lg-2 align-self-center">
        <div class='border border-0 pb-2'>
          <form method="POST" action="{% url 'articles:like_comment' comment.pk %}">
            {% csrf_token %}
            {% if request.user in comment.comment_liked_users.all %}
            <button class='btn btn-primary' type="submit">👍 좋아요</button>
            {% else %}
            <button class='btn btn-outline-primary' type="submit">👍 좋아요</button>
            {% endif %}
            <span> {{ comment.like_count }} </span>
          </form>
        </div>
        <div class='border border-0 pb-2'>
          <form method="POST" action="{% url 'articles:dislike_comment' comment.pk %}">
            {% csrf_token %}
            {% if request.user in comment.comment_disliked_users.all %}
            <button class="btn btn-danger" type="submit">👎 싫어요</button>
            {% else %}
            <button class="btn btn-outline-danger" type="submit">👎 싫어요</button>
            {% endif %}
            <span> {{ comment.dislike_count }} </span>
          </form>
        </div>
      </div>
    </div>
  </div>  
  {% endfor %}
  

  {% comment %} <form action="{% url "articles:delete" pk %}">
    <input type="submit" value="삭제">
  </form> {% endcomment %}
</div>

{% endblock content %}

gumi2inside/articles/templates/articles/poll_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>투표 수정</h2>
            {% if messages %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <br>
                <button type="submit" class="btn btn-primary">완료</button>
                <a class="btn btn-danger" href="{% url 'articles:polls_delete' poll.id %}" role="button" onclick="return confirm('삭제하시겠습니까?')">투표 삭제</a>
                <a class="btn btn-warning" href="{% url 'articles:polls_add_choice' poll.id %}" role="button">보기 추가</a>
            </form>

            <div class="choices">
                <h2 class="text-center mt-3">보기</h2>
                <hr>
                <ul class="list-group">
                    {% for choice in poll.choice_set.all %}
                    <li class="list-group-item"><a href="{% url 'articles:polls_choice_edit' choice.id %}"><i class="fas fa-pencil-alt"></i></a>&nbsp
                        {{ choice.choice_text }}</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock %}