gumi2inside/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
]

gumi2inside/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("complete/", views.complete, name="complete"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("articles_list/", views.articles_list, name="articles_list"),
    path("comment/<int:pk>/", views.comment, name="comment"),
    path("like/<int:article_pk>/", views.like_article, name="like_article"),
    path("dislike/<int:article_pk>/", views.dislike_article, name="dislike_article"),
    path("comment_like/<int:comment_pk>/", views.like_comment, name="like_comment"),
    path("comment_dislike/<int:comment_pk>/", views.dislike_comment, name="dislike_comment"),
    path('polls_list/', views.polls_list, name='polls_list'),
    path('polls_list/user/', views.polls_list_by_user, name='polls_list_by_user'),
    path('polls_add/', views.polls_add, name='polls_add'),
    path('polls_edit/<int:poll_id>/', views.polls_edit, name='polls_edit'),
    path('polls_delete/<int:poll_id>/', views.polls_delete, name='polls_delete'),
    path('polls_end/<int:poll_id>/', views.polls_endpoll, name='polls_end_poll'),
    path('polls_edit/<int:poll_id>/choice/add/', views.polls_add_choice, name='polls_add_choice'),
    path('polls_edit/choice/<int:choice_id>/', views.polls_choice_edit, name='polls_choice_edit'),
    path('polls_delete/choice/<int:choice_id>/',
         views.polls_choice_delete, name='choice_delete'),
    path('polls_<int:poll_id>/', views.poll_detail, name='polls_detail'),
    path('polls_<int:poll_id>/vote/', views.poll_vote, name='polls_vote'),
]

gumi2inside/gumi2inside/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('ciders/', include('ciders.urls')),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('announcements/', include('announcements.urls')),
    path('rboards', include('rboards.urls')),
    path('admin_img/', include('admin_img.urls')),
]

gumi2inside/rboards/urls.py
from django.urls import path
from . import views

app_name = "rboards"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("complete/", views.complete, name="complete"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("rboards_list/", views.rboards_list, name="rboards_list"),
    path("comment/<int:pk>/", views.comment, name="comment"),
    path("like/<int:article_pk>/", views.like_article, name="like_article"),
    path("dislike/<int:article_pk>/", views.dislike_article, name="dislike_article"),
    path("comment_like/<int:comment_pk>/", views.like_comment, name="like_comment"),
    path("comment_dislike/<int:comment_pk>/", views.dislike_comment, name="dislike_comment"),
]

gumi2inside/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>구미2반 커뮤니티!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" href="style.css"> {% endcomment %}
    <link rel="shortcut icon" href="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/favicon.ico">
    <style>
      .bg_top{
        width: 100%;
        height: 410px;
        background-color: #ffef6b;
        position: absoulte ;
        top: 0;
        margin-top: 70px;
      }
      .sticky-top {
        position: fixed;
        top: 0;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.98); 
      }

      .bg_top2 {
        margin-top: 70px; 
      }
      {% block style %}
      {% endblock style %}
    </style>
  </head>
  <body>
    <!-- 네비게이터 -->
    <header class="sticky-top border-bottom">
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">
                  <img src="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/logo.png" height="30px" alt="로고">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse space-between" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">홈</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'articles:articles_list' %}">익명 게시판</a>
                      </li> 
                      <li>
                        <a class="nav-link" href="{% url 'rboards:rboards_list' %}">실명 게시판</a>
                      </li>
                      <li>
                        <a class="nav-link" href="{% url 'articles:polls_list' %}">투표 게시판</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link fw-bold" style="color: #8a2be2;" href="{% url 'ciders:main' %}">사이다</a>
                      </li> 
                      {% if user.is_superuser %}
                      <li class="nav-item">
                        <a class="nav-link fw-bold" style="color: #8a2be2;" href="{% url 'amdin_img:index' %}">이미지 관리</a>
                      </li> 
                      {% endif %}
                  </ul>
                  <ul class="navbar-nav mb-2 mb-lg-0">
                      {% if request.user.is_authenticated %}
                    
                      <li class="nav-item">
                        <a class="nav-link fw-bold text-body-tertiary" href="{% url 'accounts:update' %}?next={{ request.path }}">회원정보 수정</a>
                      </li> 
                      <li class="nav-item">
                        <form action="{% url "accounts:logout" %}" method="POST">
                          {% csrf_token %}
                          <input type="submit" value="로그아웃" class="nav-link fw-bold text-body-tertiary" >
                        </form>
                      </li>

                      {% else %}
                      
                    
                      <li class="nav-item">
                        <a class="nav-link fw-bold" href="{% url 'accounts:signup' %}?next={{ request.path }}">회원가입</a>
                        </form>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link fw-bold" href="{% url 'accounts:login' %}?next={{ request.path }}">로그인</a>
                      </li> 
                      {% endif %}
                  </ul>
                
              </div>
          </div>
      </nav>
  </header>
    <!-- 네비게이터 -->
    <div class='bg_top'>
    {% block content %}
    {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>