gumi2inside/gumi2inside/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('ciders/', include('ciders.urls')),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('announcements/', include('announcements.urls')),
    path('rboards', include('rboards.urls')),
    path('admin_img/', include('admin_img.urls')),
]

gumi2inside/rboards/urls.py
from django.urls import path
from . import views

app_name = "rboards"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("complete/", views.complete, name="complete"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("rboards_list/", views.rboards_list, name="rboards_list"),
    path("comment/<int:pk>/", views.comment, name="comment"),
    path("like/<int:article_pk>/", views.like_article, name="like_article"),
    path("dislike/<int:article_pk>/", views.dislike_article, name="dislike_article"),
    path("comment_like/<int:comment_pk>/", views.like_comment, name="like_comment"),
    path("comment_dislike/<int:comment_pk>/", views.dislike_comment, name="dislike_comment"),
]

gumi2inside/rboards/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Rboard(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    textsize = models.TextField()
    red = models.TextField()
    green = models.TextField()
    blue = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    visited_count = models.IntegerField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_count = models.IntegerField(default=0)
    dislike_count = models.IntegerField(default=0)
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="real_liked_articles")
    disliked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="real_disliked_articles")
    img_url = models.TextField()
    status = models.TextField(default="Rboard")


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    origin_rboard = models.ForeignKey('Rboard', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_count = models.IntegerField(default=0)
    dislike_count = models.IntegerField(default=0)
    comment_liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="real_liked_comments")
    comment_disliked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="real_disliked_comments")

gumi2inside/rboards/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from img_upload import img_upload,img_view
from .models import Rboard, Comment
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404

@login_required
def new(request):
    return render(request, "rboards/new.html")


@login_required
def create(request):
    # print(request.user.first_name)
    title = request.POST.get("title")
    content = request.POST.get("content")
    textsize = request.POST.get("textsize")
    red = request.POST.get("red")
    green = request.POST.get("green")
    blue = request.POST.get("blue")
    # print(red,green,blue)
    rboard = Rboard(textsize=textsize, red=red, green=green, blue=blue,title=title, content=content, visited_count = 0,author=request.user)
    rboard.save()
    if 'file' in request.FILES:
        print('왔다!!')
        img_upload(request, rboard)
    return render(request, "rboards/complete.html")


@login_required
def comment(request, pk):
    content = request.POST.get("comment")
    comment = Comment(content=content)
    comment.origin_rboard = Rboard.objects.get(pk=pk)
    comment.user = request.user
    comment.save()
    return redirect(reverse('rboards:detail', kwargs={'pk': pk}))


@login_required
def complete(request):
    return redirect("rboards:rboards_list")


def detail(request, pk):
    rboard = get_object_or_404(Rboard, pk=pk)

    # 게시물의 세션 키를 생성
    session_key = f'rboard_{pk}_visited'

    # 이미 방문한 경우 조회수 증가를 막습니다.
    if session_key not in request.session:
        rboard.visited_count += 1
        rboard.save()
        # 세션에 플래그를 추가하여 중복 조회수를 방지
        request.session[session_key] = True

    time = rboard.created_at
    new_datetime = str(time)[:11] + str(time)[11:16]
    comments = rboard.comment_set.all()
    user = rboard.author
    author = user.first_name
    user_pk = user.pk
    
    context = {
        "rborad" : rboard,
        "pk": pk,
        "title": rboard.title,
        "content": rboard.content,
        "new_datetime": new_datetime,
        "comments": comments,
        "comments_count": len(comments),
        "visited_count": rboard.visited_count,
        "textsize" : rboard.textsize,
        "red" : rboard.red,
        "green" : rboard.green,
        "blue" : rboard.blue,
        "author" : author,
        "like" : rboard.like_count,
        "dislike" : rboard.dislike_count,
        'user_pk':user_pk,
        "liked_users": rboard.liked_users.all(),  # 좋아요를 누른 사용자 목록
        "disliked_users": rboard.disliked_users.all()
    }
    context = img_view(rboard,context)
    return render(request, "rboards/detail.html", context)


def rboards_list(request):
    rboards = Rboard.objects.order_by('-id')
    context = {
     'rboards' : rboards,
    }
    return render(request, "rboards/rboards_list.html", context)


@login_required
def delete(request, pk):
    rboard = Rboard.objects.get(pk=pk)
    rboard.delete()
    return redirect("rboards:rboards_list")


@login_required
def like_article(request, article_pk):
    rboard = Rboard.objects.get(pk=article_pk)
    user = request.user

    if user in rboard.liked_users.all():
        # 이미 좋아요를 누른 경우, 취소 처리
        rboard.liked_users.remove(user)
        rboard.like_count -= 1
        # rboard.visited_count -= 1
        rboard.save()
        return redirect('rboards:detail', pk=rboard.pk)
    
    if user in rboard.disliked_users.all():
        rboard.disliked_users.remove(user)
        rboard.dislike_count -= 1
    # 좋아요 처리
    rboard.liked_users.add(user)
    rboard.like_count += 1
    # rboard.visited_count -= 1
    rboard.save()
    return redirect('rboards:detail', pk=rboard.pk)


@login_required
def dislike_article(request, article_pk):
    rboard = Rboard.objects.get(pk=article_pk)
    user = request.user

    if user in rboard.disliked_users.all():
        # 이미 싫어요를 누른 경우, 취소 처리
        rboard.disliked_users.remove(user)
        rboard.dislike_count -= 1
        # rboard.visited_count -= 1
        rboard.save()
        return redirect('rboards:detail', pk=rboard.pk)
    
    if user in rboard.liked_users.all():
        rboard.liked_users.remove(user)
        rboard.like_count -= 1
    # 싫어요 처리
    rboard.disliked_users.add(user)
    rboard.dislike_count += 1
    # rboard.visited_count -= 1
    rboard.save()
    return redirect('rboards:detail', pk=rboard.pk)


@login_required
def like_comment(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    user = request.user

    if user in comment.comment_liked_users.all():
        # 이미 좋아요를 누른 경우, 취소 처리
        comment.comment_liked_users.remove(user)
        comment.like_count -= 1
    else:
        if user in comment.comment_disliked_users.all():
            comment.comment_disliked_users.remove(user)
            comment.dislike_count -= 1
        # 좋아요 처리
        comment.comment_liked_users.add(user)
        comment.like_count += 1
        
    rboard = comment.origin_rboard
    # rboard.visited_count -= 1
    rboard.save()
    comment.save()
    return redirect('rboards:detail', pk=rboard.pk)


@login_required
def dislike_comment(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    user = request.user

    if user in comment.comment_disliked_users.all():
        # 이미 싫어요를 누른 경우, 취소 처리
        comment.comment_disliked_users.remove(user)
        comment.dislike_count -= 1
    else:
    
        if user in comment.comment_liked_users.all():
            comment.comment_liked_users.remove(user)
            comment.like_count -= 1
        # 싫어요 처리
        comment.comment_disliked_users.add(user)
        comment.dislike_count += 1
    rboard = comment.origin_rboard
    # rboard.visited_count -= 1
    rboard.save()
    comment.save()
    return redirect('rboards:detail', pk=rboard.pk)

gumi2inside/rboards/templates/rboards/complete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="d-flex flex-column text-center">
    <h1 class="fw-bold">이얏호~ 글이 작성되었어용~</h1>
    <a style="text-decoration:none; color: #8a2be2;" href="{% url "rboards:rboards_list" %}"><h1 class="fw-bold text-#8a2be2">보러 가볼까요?~</h1></a>
    <a style="text-decoration:none; color: #8a2be2;" href="{% url "rboards:rboards_list" %}"><img src="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/complete.png" class="img-fluid mx-5" alt="..."></a>
</div>
{% endblock content %}

gumi2inside/rboards/templates/rboards/detail.html
{% extends "base.html" %}
{% load humanize %}
{% load rboards_custom_tag %}
{% block style %}
.bg_top_2{
  width: 100%;
  height: 330px;
  background-color: white;
  position: absoulte ;
  top: 0;
  margin: 0;
}
.bg-yellow{
  background-color: #ffe651;
}
.bg-realgrey{
  border: 1px solid lightgrey;
}

{% endblock style %} 

{% block content %}
<div class='bg_top_2'>
  <div class="container mt-5 mb-3">
    <div>
      <strong class="text-break"> {{ title }}</strong>
      <span style="float: right;">작성자 : {{ author }}</span>
      <div style="clear: both;"></div>
      <hr>
    </div>
    {% if img_url %}
      <img src="{{ img_url }}" alt="image" style="max-width: 90%;">
    {% endif %}
      <div>
        <!--여기에 클래스 추가-->
        <p class="text-break" style="color: rgb({{red|safe}}, {{green|safe}}, {{blue|safe}}); font-size : {{textsize|safe}}px; white-space: pre-line" > {{content|urlize|safe|target_blank}}</p>
      </div>
      <hr>
      <span style="float: right;">작성시간 : {{ new_datetime }}</span>
    <p>조회수 : {{visited_count}} </p>
    <div class="row">
      <div class='col-3 border border-0'>
        <form method="POST" action="{% url 'rboards:like_article' pk %}">
          {% csrf_token %}
          {% if request.user in liked_users %}
          <button class='btn btn-primary border border-0' type="submit">🧡 추천!</button>
          {% else %}
          <button class='btn btn-outline-primary' type="submit">🧡 추천!</button>
          {% endif %}
          <span> {{ like }} </span>
        </form>
      </div>
      {% comment %} <div class='col-3 border border-0'>
        <form method="POST" action="{% url 'rboards:dislike_article' pk %}">
          {% csrf_token %}
          {% if request.user in disliked_users %}
          <button class="btn btn-danger" type="submit">👎 비추</button>
          {% else %}
          <button class="btn btn-outline-danger" type="submit">👎 비추</button>
          {% endif %}
          <span> {{ dislike }} </span>
        </form>
      </div> {% endcomment %}
    </div>
  </div>
  <div class="container mt-5">
    <strong>댓글 ({{comments_count}}) </strong>
    <form action="{% url 'rboards:comment' pk %}" method="POST">
      {% csrf_token %}
      <textarea name="comment" id="comment" row="3" style="width: 100%;"></textarea>
      <input class="btn btn-light btn-lg text-center me-5" type="submit" value="댓글 쓰기">
      
    </form>
  </div>
  {% for comment in comments %}
    <div class="container my-4 pt-4 pb-2 px-5 bg-light bg-realgrey">
      <div class="row">
        <div class='col-8 col-md-9 col-lg-10 align-self-center'>
          <div class="mb-3">
            <p><span class="pe-3">{{ comment.created_at }}</span> <span class="border border-dark-subtle"></span> <span class="ps-3 text-body-tertiary">{{ comment.user.first_name }}</span> </p>
          </div>
          <div class="my-2 mx-5 text-break" style="white-space: pre-line">{{comment.content|urlize|safe|target_blank}} </div>
        </div>
        <div class="col-4 col-md-3 col-lg-2 align-self-center">
          <div class='border border-0 pb-2'>
            <form method="POST" action="{% url 'rboards:like_comment' comment.pk %}">
              {% csrf_token %}
              {% if request.user in comment.comment_liked_users.all %}
              <button class='btn btn-primary' type="submit">👍 좋아요</button>
              {% else %}
              <button class='btn btn-outline-primary' type="submit">👍 좋아요</button>
              {% endif %}
              <span> {{ comment.like_count }} </span>
            </form>
          </div>
          <div class='border border-0 pb-2'>
            <form method="POST" action="{% url 'rboards:dislike_comment' comment.pk %}">
              {% csrf_token %}
              {% if request.user in comment.comment_disliked_users.all %}
              <button class="btn btn-danger" type="submit">👎 싫어요</button>
              {% else %}
              <button class="btn btn-outline-danger" type="submit">👎 싫어요</button>
              {% endif %}
              <span> {{ comment.dislike_count }} </span>
            </form>
          </div>
        </div>
      </div>
    </div>  
  {% endfor %}
  

  {% comment %} <form action="{% url "rboards:delete" pk %}">
    <input type="submit" value="삭제">
  </form> {% endcomment %}
</div>

{% endblock content %}

gumi2inside/rboards/templates/rboards/new.html
{% extends "base.html" %}
{% load static %}
{% block style %}
.div {
  width: 100%;
}

.input1{
  border: 2px solid black
  border-radius : 5px;
  background-color: #ffef6b;
}

.my-hr2 {
  border: 2;
  height: 2px;
}
.btn1{
  background-color:#8c99a8;
  color:white;
}

.btn1:hover {
  background-color:#3396f4;
  color:white;
}  

{% endblock style %}

{% block content %}
<div class="container pt-3">
  <div class="div bg-light border py-3 shadow-lg">
    <div>
    <h2 class="m-3" style="text-align:center;"><strong>글쓰기</strong></strong></h2>
    </div>
    <hr class="mx-3 my-hr2">
    <form action="{% url "rboards:create" %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}  <!--POST 요청시 필요한 요소-->
      <div class="mx-3">
        <input type="text" placeholder=" 제목" id="title" name="title" style="width: 100%;"> 
      </div>
      <p></p>
      <hr class="mx-3 my-hr2">
      <div class="mx-3">
        <textarea name="content" placeholder=" 내용" id="content" cols="30" rows="16" style="width: 100%;"></textarea>
      </div>
      <div>
        <input class="ps-3" type="file" name="file" accept="image/*">
      </div>
      {% comment %}  {% endcomment %}
      <div class="mx-3 d-flex">
        <div class="form-group text-center d-flex justify-content-center align-items-center" >
          <label for="textsize" class="me-3">글 크기</label>
          <select class="form-control text-center p-0" style="width:50px; height:40px;" id="textsize" name="textsize">
              <option value="16">16</option>
              <option value="20">20</option>
              <option value="24">24</option>
              <option value="30">30</option>
              <option value="34">34</option>
              <option value="48">48</option>
              <option value="60">60</option>
              <option value="72">72</option>
          </select>
      </div>
      <div class="form-group text-center mx-4 d-flex justify-content-center align-items-center">
          <div class="mx-3">
              <label for="red">Red:</label>
              <input type="range" id="red" name="red" min="0" max="255" value="0">
              <span id="redValue">0</span>
          </div>
  
          <div class="mx-3">
              <label for="green">Green:</label>
              <input type="range" id="green" name="green" min="0" max="255" value="0">
              <span id="greenValue">0</span>
          </div>
  
          <div class="mx-3">
              <label for="blue">Blue:</label>
              <input type="range" id="blue" name="blue" min="0" max="255" value="0">
              <span id="blueValue">0</span>
          </div>
  
      <!-- 선택한 RGB 색상 표시 칸 -->
      <div>
          <div id="colorDisplay"  class="mx-3" style="width: 30px; height: 30px; border: 1px solid #000;"></div>
      </div>
      </div>
      </div>
      {% comment %}  {% endcomment %}
      <div class="d-grid gap-2 mx-3 mt-2">
        <input class="btn btn1" type="submit" value="제출"></input>
      </div>
    </form>
  </div>
  </div>

  <!-- 이 밑에서 작업해야 할듯 함 -->
  <script>
    var backgroundCh = function () {
        var sel = document.getElementById('textcolor');
        //sel.style.backgroundColor = sel.value;
      };

    const redSlider = document.getElementById("red");
    const greenSlider = document.getElementById("green");
    const blueSlider = document.getElementById("blue");
    const redValue = document.getElementById("redValue");
    const greenValue = document.getElementById("greenValue");
    const blueValue = document.getElementById("blueValue");
    const colorDisplay = document.getElementById("colorDisplay");

    redSlider.addEventListener("input", updateColor);
    greenSlider.addEventListener("input", updateColor);
    blueSlider.addEventListener("input", updateColor);

    function updateColor() {
        const red = redSlider.value;
        const green = greenSlider.value;
        const blue = blueSlider.value;

        redValue.textContent = red;
        greenValue.textContent = green;
        blueValue.textContent = blue;

        const rgbColor = `rgb(${red},${green},${blue})`;
        colorDisplay.style.backgroundColor = rgbColor;
    }
    </script>
    {% endblock content %}

gumi2inside/rboards/templates/rboards/rboards_list.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block style %}
.imagesize{
  height: 300px;
  width: 300px;
  margin-top: 0px;
  
}
{% endblock style %}
{% block content %}
{% for rboard in rboards%}
<div class="container col-12">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="bg-white border border-black border-3 rounded-2 text-black mt-5">
        <div class='row justify-content-betwwen'>
          <span class='col-8 col-md-9 row justify-content-start mx-0'>
            <div class='row justify-content-center'>
              <a class='col-11 text-start text-truncate fs-3 text-decoration-none text-black' href="{% url 'rboards:detail' rboard.pk%}"> {{ rboard.title }} </a>
            </div>
            <div class='col-12 row justify-content-start mb-2'>
              <span class='col-4 col-lg-3 col-xl-2 text-end text-body-tertiary border-end'>{{ rboard.author.first_name }}</span>
              <span class='col-5 col-lg-6 col-xl-7 text-start text-body-tertiary border-start'>{{ rboard.created_at|time_difference_with_now }}</span>
            </div>
          </span>
          <span class='col-4 col-md-3 row justify-content-end align-items-center mx-0'>
            <p class='col-9 mb-0 pt-2'>🧡{{ rboard.like_count }}</p>
            <p class='col-9 mb-1 pb-2'>💬{{ rboard.comment_set.all|length }}</p>
          </span>
        </div>   
      </div>
    </div>
  </div>
</div>
{% endfor %}


<a href="{% url 'rboards:new' %}" style="float: right;"><img src="https://gumi2inside.s3.ap-northeast-2.amazonaws.com/Static/gcova.png" class='imagesize fixed-bottom '></a>
{% endblock content %}