gumi2inside/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
]

gumi2inside/gumi2inside/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('ciders/', include('ciders.urls')),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('announcements/', include('announcements.urls')),
    path('rboards', include('rboards.urls')),
    path('admin_img/', include('admin_img.urls')),
]

gumi2inside/rboards/urls.py
from django.urls import path
from . import views

app_name = "rboards"
urlpatterns = [
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("complete/", views.complete, name="complete"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("rboards_list/", views.rboards_list, name="rboards_list"),
    path("comment/<int:pk>/", views.comment, name="comment"),
    path("like/<int:article_pk>/", views.like_article, name="like_article"),
    path("dislike/<int:article_pk>/", views.dislike_article, name="dislike_article"),
    path("comment_like/<int:comment_pk>/", views.like_comment, name="like_comment"),
    path("comment_dislike/<int:comment_pk>/", views.dislike_comment, name="dislike_comment"),
]

gumi2inside/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

gumi2inside/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm,UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name','last_name' ,'email',)

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']  # first_name 값 저장
        user.last_name = self.cleaned_data['last_name']    # last_name 값 저장
        if commit:
            user.save()
        return user

gumi2inside/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm
from django.shortcuts import get_object_or_404
from .models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from .forms import CustomUserCreationForm

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        next_url = request.GET.get('next')
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect( next_url or 'home')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request,'accounts/login.html',context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('home') 

@login_required
def update(request):

    if request.method =='POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,

    }
    return render(request, 'accounts/update.html', context)
@login_required
def change_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = PasswordChangeForm(request.user)
    context={
        'form' : form,
     
    }
    return render(request, 'accounts/change_password.html', context)


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            print(request.POST.get('first_name'))
            print(request.POST.get('last_name'))
            print("POST 데이터:", request.POST)
            print("클린 데이터:", form.cleaned_data)
            print("first_name:", form.cleaned_data.get('first_name'))
            print("last_name:", form.cleaned_data.get('last_name'))
            
            form.save()
            return redirect('/')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)
@login_required
def delete(request):
    request.user.delete()
    return redirect('/')

gumi2inside/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block style %}
<style>
    /* 여기에 추가적인 CSS 스타일을 정의하세요 */

    /* 노란색 배경의 높이를 조절하여 노란색 배경과 겹치지 않게 합니다. */
    .bg_top {
        height: 200px; /* 원하는 높이로 조절하세요 */
    }

    /* 카드를 가운데 정렬하고 크기를 조절합니다. */
    .custom-card {
        max-width: 100%;
        margin: 0 auto;
        background-color: #fff; /* 카드 배경색 설정 */
        padding: 0px; /* 카드 내용과의 간격 설정 */
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1); /* 카드 그림자 추가 (선택 사항) */
        position: relative; /* 카드를 상대적으로 위치시킴 */
        top: 60px; /* 카드를 위로 이동하여 노란 배경과 겹치지 않게 함 */
    }

    .card-header {
        {% comment %} background-color:  #f0f0f0;        {% endcomment %}
        color: black;
    }

    /* 필요한 다른 스타일을 추가하세요 */
</style>
{% endblock style %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card custom-card"> <!-- "custom-card" 클래스 추가 -->
                <div class="card-header">
                    <h1 class="text-center">비밀번호 변경</h1>
                </div>
                <div class="card-body m-5">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.old_password.id_for_label }}" class="form-label">현재 비밀번호:</label>
                            <input type="password" name="{{ form.old_password.name }}" id="{{ form.old_password.id_for_label }}" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="{{ form.new_password1.id_for_label }}" class="form-label">새 비밀번호:</label>
                            <input type="password" name="{{ form.new_password1.name }}" id="{{ form.new_password1.id_for_label }}" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="{{ form.new_password2.id_for_label }}" class="form-label">새 비밀번호 확인:</label>
                            <input type="password" name="{{ form.new_password2.name }}" id="{{ form.new_password2.id_for_label }}" class="form-control" required>
                        </div>

                        <button type="submit" class="btn " style="background-color: #87CEEB; color: white;">변경</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

gumi2inside/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1 class="container text-center pt-5 pb-2">구미2반</h1>
<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="d-flex flex-column align-items-center row">
            <div class="form-floating col-8 my-2">
                <input class="form-control" id="아이디" type="text" name="username" placeholder="아이디" autofocus autocapital="none" autocomplete="username" maxlength="24" required id="id_username">
                <label for="아이디">아이디</label>
            </div>
            <div class="form-floating col-8 mb-2">
                <input class="form-control" id="비밀번호" type="password" name="password" placeholder="비밀번호" autocomplete="current-password" required id="id_password">
                <label for="비밀번호">비밀번호</label>
            </div>
            <div class="form-floating col-8 mt-3">
                <button class="btn col-12 btn-lg p-0 btntag" type="submit">로그인</button>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

gumi2inside/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block style %}
<style>
  .container {
    max-width: 400px;
    margin: 0 auto;
    background-color: #f8f9fa;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  .form-label {
    font-weight: bold;
  }

  .mb-3 {
    margin-bottom: 1.5rem;
  }

  .btn1{
    background-color:#8c99a8;
    color:white;
  }
  
  .btn1:hover {
    background-color:#3396f4;
    color:white;
  }  
</style>
{% endblock style %}

{% block content %}
<div class="container pt-3">
    <div class="div bg-light border py-3 shadow-lg">
    <h2 class="m-3" style="text-align:center;"><strong>회원가입</strong></h2>
    <hr class="mx-3">
    <form action="{% url "accounts:signup" %}" method="POST">
        {% csrf_token %}
        <div class="mb-3 mx-3">
            <input type="text" class="form-control" placeholder="아이디" name="username" maxlength="24" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
            <span class="form-text mx-1">※ 24자 이하 문자, 숫자, @/./+/-/_만 가능</span>
        </div>
        <div class="mb-3 mx-3">
            <input type="text" class="form-control" placeholder="이름" name="first_name" id="id_first_name">
        </div>
        <div class="mb-3 mx-3">
            <input type="text" class="form-control" placeholder="닉네임" name="last_name" id="id_last_name">
        </div>
        <div class="mb-3 mx-3">
            <input type="password" class="form-control" placeholder="비밀번호" name="password1" autocomplete="new-password" required id="id_password1">
        </div>
        <div class="mb-3 mx-3">
            <input type="password" class="form-control" placeholder="비밀번호 확인" name="password2" autocomplete="new-password" required id="id_password2">
        </div>
        <div class="mb-3 mx-3">
            <span class="mx-1">※ 다음과 같은 비밀번호는 사용할 수 없습니다:</span>
            <ul>
                <li>아이디와 유사함</li>
                <li>8자 미만</li>
                <li>통상적으로 자주 사용됨</li>
                <li>숫자로만 이루어짐</li>
            </ul>
        </div>
        <div class="d-grid gap-2 mx-3 mt-2">
            <input class="btn btn1" type="submit" value="회원가입" id="signupButton"></input>
          </div>
    </form>
    </div>
</div>
{% endblock content %}

gumi2inside/accounts/templates/accounts/update.html
{% extends "base.html" %}
{% block style %}
<style>
    /* 여기에 추가적인 CSS 스타일을 정의하세요 */

    /* 노란색 배경의 높이를 조절하여 노란색 배경과 겹치지 않게 합니다. */
    .bg_top {
        height: 200px; /* 원하는 높이로 조절하세요 */
    }

    /* 카드를 가운데 정렬하고 크기를 조절합니다. */
    .custom-card {
        max-width: 100%;
        margin: 0 auto;
        background-color: #fff; /* 카드 배경색 설정 */
        padding: 0px; /* 카드 내용과의 간격 설정 */
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1); /* 카드 그림자 추가 (선택 사항) */
        position: relative; /* 카드를 상대적으로 위치시킴 */
        top: 60px; /* 카드를 위로 이동하여 노란 배경과 겹치지 않게 함 */
    }

    .card-header {
        {% comment %} background-color:  #f0f0f0;        {% endcomment %}
        color: black;
    }

    /* 필요한 다른 스타일을 추가하세요 */
</style>
{% endblock style %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card custom-card"> <!-- "custom-card" 클래스 추가 -->
                <div class="card-header">
                    <h1 class="text-center">회원정보 수정</h1>
                </div>
                <div class="card-body m-5">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                          <label for="id_first_name" class="form-label">이름:</label>
                          <input type="text" name="first_name" id="id_first_name" class="form-control" value="{{ user.first_name }}">
                      </div>

                      <div class="mb-3">
                        <label for="id_last_name" class="form-label">별명:</label>
                        <input type="text" name="last_name" id="id_last_name" class="form-control" value="{{ user.last_name }}">
                    </div>

                    <div class="mb-3">
                      <label for="id_email" class="form-label">메일:</label>
                      <input type="email" name="email" id="id_email" class="form-control" value="{{ user.email }}">
                  </div>

                        <div class="d-flex justify-content-between">
                          <button type="submit" class="btn " style="background-color: #87CEEB; color: white;">변경</button>
                            <a href="{% url 'accounts:change_password' %}" class="btn btn-secondary" style="background-color: #87CEEB; color: white;">비밀번호 변경</a>
                        </div>
                    </form>
                  
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}